### ISSUE TITLE
Response Threshold

### ISSUE THREAD

**Issue by datawookie** [MeganBeckett/lubridate-heatmaps_tutorial#3]
Hi!

How did you arrive at the response threshold of 0.0807? Is this some magic number? :)

Best regards,
Andrew.

**Comment by MeganBeckett** [comment]
Mmm, yes, the number is actually unrelated - I calculated it as the proportion of loan applicants who did not repay their loans in the training set (ie. 8%).  I realise I was confusing some concepts here, and have reworked this step, plus a bit more in repsonse to your other comment too so that I can better evaluate the logistic regression model.
